### ISSUE TITLE
Feature request: ask_password

### ISSUE THREAD

**Issue by drazisil** [your-tools/python-cli-ui#16]
This package is beautiful, and I would love to switch all my input to it.

I didn't see a way to ask for a password though. It would be the same as `ask_string`, but with either no echo, or a mask.

My apologies if the feature already exists, I'll look into creating a PR in a couple days if this is something you are ok with.

**Comment by dmerejkowsky** [comment]
> This package is beautiful.

Thanks :) That is really appreciated.

I took a look at your PR. It looks great !
