### ISSUE TITLE
info_table tabulate wrapper can't do headers=keys like tabulate can

### ISSUE THREAD

**Issue by Jackbennett** [your-tools/python-cli-ui#57]
```python
cli_ui.info_table({"Name": ["Alice", "Bob"],"Age": [24, 19]}, headers="keys")
0    1    2    3
---  ---  ---  ---
N    a    m    e
A    g    e

print(tabulate.tabulate({"Name": ["Alice", "Bob"],"Age": [24, 19]}, headers="keys"))
Name      Age
------  -----
Alice      24
Bob        19
```

Some more documentation of how info_table is expected to have data mapped into it would be very useful

**Comment by dmerejkowsky** [comment]
Note that the code will still not run with `cli_ui` because `cli_ui` expects each element of tabulate's data to be a list of tokens.

So you'll need something like:

```python
data = {
    (cli_ui.bold, "Name"): [(cli_ui.green, "Alice"), (cli_ui.green, "Bob")],
    (cli_ui.bold, "Age"): [(cli_ui.blue, 24), (cli_ui.blue, 9)],
}
cli_ui.info_table(data)
```

Or, if you actually don't need the rows and columns to be colored at all:

```python
import tabulate
import cli_ui

data = {"Name": ["Alice", "Bob"], "Age": [24, 9]}
message = tabulate.tabulate(data, headers="keys")
cli_ui.info(message)
```

**Comment by Jackbennett** [comment]
I hacked in [data[row]](https://gist.github.com/Jackbennett/20735d525c1f76b791b513a002556903#file-cli_ui_info_table-py-L10) temporarily which mostly works but wanted to make it simpler for a MR. 

I'm afraid to say I replaced cli_ui for rich as I needed heavier output work than I had thought at first.

**Comment by dmerejkowsky** [comment]
Well, your hack is "almost" what I did in #58.

> I'm afraid to say I replaced cli_ui for rich as I needed heavier output work than I had thought at first.

Don't worry -it happens - Thanks for taking the time to open an issue :)

**Comment by Jackbennett** [comment]
I was just looking at that MR. looks like you nicely handled a few other things too. 

Your answer plus that MR landing I'd see this issue as answered. I haven't hit close I presume that MR will close it. otherwise feel free to knock this issue off as resolved. Thank you.
