### ISSUE TITLE
Doc link broken

### ISSUE THREAD

**Issue by Maofryy** [your-tools/python-cli-ui#60]
Hi @dmerejkowsky,
It seems that the [python-cli-ui documentation](https://tankerhq.github.io/python-cli-ui) link is broken.
I found the [docs](https://github.com/dmerejkowsky/python-cli-ui/blob/master/docs/index.rst) nicely generated but maybe not hosted on github pages ?
Might need to review the call of ghp-import in [deploy.sh](https://github.com/dmerejkowsky/python-cli-ui/blob/master/docs/deploy.sh).

**Comment by dmerejkowsky** [comment]
That's because the project has moved outside of the TankerHQ organization. This should be fixed now.

New link is : https://dmerejkowsky.github.io/python-cli-ui/
