### ISSUE TITLE
Text coloring doesn't work

### ISSUE THREAD

**Issue by LukaAdjovic** [your-tools/python-cli-ui#70]
Whenever I want to test the coloring from documentation's example such as
`cli_ui.info(
  "This is",
  cli_ui.red, "red", cli_ui.reset,
  "and this is",
  cli_ui.bold, "bold"
)
`
it doesn't color it and just outputs a normal white string

**Comment by dmerejkowsky** [comment]
Are you on Windows? If so, you have to opt-in by calling `cli_ui.setup()` with `color="always"`

I should probably update the documentation about that ...

**Comment by LukaAdjovic** [comment]
Yes, couldn't find anything about it in the documentation so I thought about posting an issue here. Anyway the problem is fixed. Thanks!

**Comment by dmerejkowsky** [comment]
> Yes, couldn't find anything about it in the documentation so I thought about posting an issue here

That's how one keeps documentation up-to-date and relevant :)

Could you please tell me what you think about the doc update in #71 ?
