### ISSUE TITLE
Document how to use cli_ui in a concurrent context

### ISSUE THREAD

**Issue by dmerejkowsky** [your-tools/python-cli-ui#77]
The first way I can think of is something like:

```python
stdout_lock = threading.RLok()
with stdout_lock:
    cli_ui.info(...)
```

which is what is used in https://github.com/dmerejkowsky/tsrc/

But maybe we can be more clever and do some tricks with the `fileobj` parameter?

Also, async?

**Comment by dmerejkowsky** [comment]
So I wrote examples using cli-ui concurrently, both with threads and async code - and I don't think we can do better than having the lock managed by the API user. 

The code is here: ['examples/' folder on the 'concurrent' branch](https://github.com/dmerejkowsky/python-cli-ui/tree/concurrent/examples).

**Comment by cgestes** [comment]
Oh if you want to have a serie of ui.info() call to form a lign they have to be protected by a lock somehow or print to their own buffer. I missed that 😅

Cool for the examples. 👍

**Comment by gdubicki** [comment]
Nice examples, thanks! 

One minor issue: `import time` in `asynchronous.py` is unused.

**Comment by dmerejkowsky** [comment]
Fixed. Thanks.
