### ISSUE TITLE
Feature request multi select choices

### ISSUE THREAD

**Issue by cunyap** [your-tools/python-cli-ui#84]
Hi,

Great tool! If I read the documentation correctly there is currently no way for multiple selections/answers for the `ask_choice` method. 
It would be really great to have this option. Any ideas on how to implement this easily?

**Comment by dmerejkowsky** [comment]
> Great tool!

Thanks :)

> Any ideas on how to implement this easily?

Probably use one of the libs mentioned here: 

https://stackoverflow.com/questions/45022566/create-python-cli-with-select-interface

Do you want to try and work on a patch ?

**Comment by cunyap** [comment]
Thanks, I saw those. 
However, at least some would not work on Windows platforms, and ideally, it should work cross-platform.

Sure - I was thinking of just allowing for a comma-separated list for `ask_choice` as a way for multiple input selection i.e. 1,3. Would that be acceptable?

**Comment by dmerejkowsky** [comment]
I think the API would be cleaner with a separate `select_choices` function instead, especially if the functionality turns out to not be implemented for certain platforms.

**Comment by cunyap** [comment]
Sure. Please find my implementation here #85
