### ISSUE TITLE
Doc: how do we import it?

### ISSUE THREAD

**Issue by cgestes** [your-tools/python-cli-ui#9]
imports are not mentioned in the documentation.

tried to import 'python-cli-ui' which seems strange!

**Comment by dmerejkowsky** [comment]
The 'ui' prefix in virtually *all* the code samples should give you a clue, no ?

But yeah, we should document this somewhere :)

**Comment by cgestes** [comment]
yes. but it seems strange for newcomers that the project name is not what you import.

if ui is available on pip it would make sense to use it.

cause anyway if you have python-cli-ui installed you cannot use the ui module for something else.

**Comment by cgestes** [comment]
also... a little unrelated, but the documentation link (the most useful information) is at the bottom, can we move it to the top?

**Comment by dmerejkowsky** [comment]
will do
